package Assignment6View;

import Assignment6Controller.AccountTransactionDTO;
import Assignment6Controller.BankAccountDTO;
import Assignment6Controller.CustomerDTO;
import Assignment6Model.BankAccount;
import Assignment6Model.BankCustomer;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class TransactionSummarySearch extends javax.swing.JFrame{

        /**
         * Creates new form TransactionSummary
         */
        public TransactionSummarySearch() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jList1 = new javax.swing.JList<>();
            jLabel2 = new javax.swing.JLabel();
            accIDBox = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            custNameBox = new javax.swing.JTextField();
            jButton1 = new javax.swing.JButton();
            search = new javax.swing.JButton();
            jLabel4 = new javax.swing.JLabel();
            transactionList = new ArrayList();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jLabel1.setText("Accout ID:");

            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                public int getSize() { return transactionList.size(); }
                public String getElementAt(int i) { return transactionList.get(i).toString(); }
            });
            jScrollPane1.setViewportView(jList1);

            jLabel2.setText("Transactions:");

            accIDBox.setText("acctID");


            search.setText("Search");
            search.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    accountSelected = null;
                    BankAccountDTO getter = new BankAccountDTO();
                   accountSelected= getter.BankAccountByID(Integer.parseInt(accIDBox.getText()));
                    if(accountSelected ==null){
                        JOptionPane.showMessageDialog(null, "Error, no transactions found with that account ID");
                    }else{
                        //searches for customer name via customerDTO and returns the name
                        custNameBox.setText(getcustName());
                        AccountTransactionDTO tgetter = new AccountTransactionDTO();
                        transactionList = tgetter.transactionListByID(accountSelected.getAccountNum());
                        jList1.setModel(new javax.swing.AbstractListModel<String>() {
                            public int getSize() { return transactionList.size(); }
                            public String getElementAt(int i) { return transactionList.get(i).toString(); }
                        });
                    }
                }
            });

            jLabel3.setText("Customer Name:");

            custNameBox.setText("CustName");
            custNameBox.setEditable(false);

            jButton1.setText("Done");
            //when user presses done it will hide the window
            jButton1.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setVisible(false);
                }
            });

            jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
            jLabel4.setText("Transaction Summary");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(31, 31, 31)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jScrollPane1)
                                                            .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addComponent(jLabel4)
                                                                            .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(jLabel1)
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                    .addComponent(accIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(30, 30, 30)
                                                                                    .addComponent(jLabel3)))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(custNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(64, 64, 64)
                                                    .addComponent(search)
                                                    .addGap(64, 64, 64)
                                                    .addComponent(jButton1)))
                                    .addContainerGap(31, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(accIDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(custNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Wrap the buttons in a parallel horizontal group
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addComponent(search)))
                                    .addContainerGap(16, Short.MAX_VALUE)

                            )
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Assignment6View.TransactionSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Assignment6View.TransactionSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Assignment6View.TransactionSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Assignment6View.TransactionSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Assignment6View.TransactionSummary().setVisible(true);
                }
            });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JList<String> jList1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField accIDBox;
        private javax.swing.JTextField custNameBox;
    private javax.swing.JButton search;
    public static BankAccount accountSelected;
    public static ArrayList transactionList;



    public String getcustName(){
        CustomerDTO t = new CustomerDTO();
        BankCustomer tt = t.customerByID(accountSelected.getCustID());
        return tt.getFirstName() + " " + tt.getLastName();
    }


        // End of variables declaration//GEN-END:variables

}
